// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFaeY-nzpsuTj26fjVJaJgKjrbImz-8PI',
    appId: '1:415267844288:android:78589aa19fb7fe85c87d25',
    messagingSenderId: '415267844288',
    projectId: 'mvp-builder-529af',
    storageBucket: 'mvp-builder-529af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCo_tgXfdxJmX69obUszn6AhBpQDUXeE',
    appId: '1:415267844288:ios:ac2b63cbea2a03fcc87d25',
    messagingSenderId: '415267844288',
    projectId: 'mvp-builder-529af',
    storageBucket: 'mvp-builder-529af.firebasestorage.app',
    iosBundleId: 'com.example.mvpBuilder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihS_-GS15NDsrnKlOTeL7MiJoRZPUprM',
    appId: '1:415267844288:web:478d1db3c9c3a3cac87d25',
    messagingSenderId: '415267844288',
    projectId: 'mvp-builder-529af',
    authDomain: 'mvp-builder-529af.firebaseapp.com',
    storageBucket: 'mvp-builder-529af.firebasestorage.app',
    measurementId: 'G-3C9EQCQ9XE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCo_tgXfdxJmX69obUszn6AhBpQDUXeE',
    appId: '1:415267844288:ios:ac2b63cbea2a03fcc87d25',
    messagingSenderId: '415267844288',
    projectId: 'mvp-builder-529af',
    storageBucket: 'mvp-builder-529af.firebasestorage.app',
    iosBundleId: 'com.example.mvpBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihS_-GS15NDsrnKlOTeL7MiJoRZPUprM',
    appId: '1:415267844288:web:48cbe7d54e00b619c87d25',
    messagingSenderId: '415267844288',
    projectId: 'mvp-builder-529af',
    authDomain: 'mvp-builder-529af.firebaseapp.com',
    storageBucket: 'mvp-builder-529af.firebasestorage.app',
    measurementId: 'G-1XCE8ZE0KM',
  );

}